// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdpFiVcSHRn3a3U89cQjdIRDEJpTvlJc',
    appId: '1:975361758525:web:f952320d157b2f55a02154',
    messagingSenderId: '975361758525',
    projectId: 'fir-notifications-bb92a',
    authDomain: 'fir-notifications-bb92a.firebaseapp.com',
    storageBucket: 'fir-notifications-bb92a.appspot.com',
    measurementId: 'G-FE85XWQWDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3safXywbf4IWrVX3RMNMLfzJD5EETPOo',
    appId: '1:975361758525:android:ad5cf7e9eeabc89ea02154',
    messagingSenderId: '975361758525',
    projectId: 'fir-notifications-bb92a',
    storageBucket: 'fir-notifications-bb92a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKHs6OkckdoiWqhg2xnzPs8tslLHwpk20',
    appId: '1:975361758525:ios:e10d3d4ecf25e0aca02154',
    messagingSenderId: '975361758525',
    projectId: 'fir-notifications-bb92a',
    storageBucket: 'fir-notifications-bb92a.appspot.com',
    iosBundleId: 'com.example.firebaseNotifications',
  );
}
